#!/bin/bash
executable_filename=../blast/bin/programs/quintessence_from_yaml
[ -f $executable_filename ] && echo "Found" || echo "The needed executable $executable_filename was not found"
find . -path "./quintessence/*.yml" | xargs $executable_filename
